# prowl-github-app configuration. Place in default branch

version: '0.1.0'

targets:
  - id: markdown
    stalk:
      paths:
        - "**/*.md"
      base: master
    pounce:
      reviewers: []
      merge_method: merge

