# prowl-github-app configuration. Place in default branch

version: '0.1.0'

pull_requests:
  - id: catchall
    spec:
      paths:
        - "**/*"
      base: master
    constrain:
      reviewers: []
  - id: markdown
    spec:
      paths:
        - "**/*.md"
      base: master
    constrain:
      reviewers:
        - tommilligan
        - tommilligan-plutoflume

