# prowl-github-app configuration. Place in default branch

version: '0.1.0'

targets:
  - id: docs
    stalk:
      paths:
        - "**/*.md"
      base: master
    pounce:
      action: status
      auto_pounce: true
      author_implicit_reviewer: true
      commit_message_pr_number: true
      reviewers:
        - tommilligan
      merge_method: merge
      not_ready_labels:
        - WIP
        - nomerge

  - id: code
    stalk:
      paths:
        - "**/*.py"
      base: master
    pounce:
      reviewers:
        - tommilligan
        - tommilligan-plutoflume
      merge_method: merge

