# prowl-github-app configuration. Place in default branch

version: '0.1.0'

targets:
  - id: markdown
    stalk:
      paths:
        - "**/*.md"
      base: master
    pounce:
      author_implicit_reviewer: true
      check_delay: 0
      reviewers:
        - tommilligan
      merge_method: merge

