version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.3-browsers
    steps:
      - checkout
      - run: sleep 15s
  test:
    docker:
      - image: circleci/node:8.11.3-browsers
    steps:
      - checkout
      # - run: if (( RANDOM % 2 )); then false; fi
      - run: sleep 5s
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test

