version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.3-browsers
    steps:
      - checkout
      - run: sleep 60s
  test:
    docker:
      - image: circleci/node:8.11.3-browsers
    steps:
      - checkout
      - run: sleep 3s
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test

